project_id = "tffcowprbgnvvjpjadfs"

[functions.check-now]
verify_jwt = true

[functions.price-watch]
verify_jwt = false

[functions.purge-deleted-trips]
verify_jwt = false

[functions.price-nudge]
verify_jwt = false

[functions.parse-magic-paste]
verify_jwt = true

[functions.contact-message]
verify_jwt = false

[functions.delta-manage-scrape]
verify_jwt = true

[functions.check-delta-fare]
verify_jwt = true
